import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('https://avagamya.vercel.app/');
    await page.getByRole('link', { name: 'Home' }).click();
    await page.getByRole('link', { name: 'Staff Access' }).click();
    await page.locator('div').filter({ hasText: /^Data Protection Officer$/ }).nth(1).click();
    await page.getByRole('textbox', { name: 'DPO Username' }).click();
    await expect(page.locator('form')).toContainText('Verify Access');
    await page.getByRole('textbox', { name: 'DPO Username' }).fill('dpo_admin');
    await page.getByRole('textbox', { name: 'Access Key' }).fill('avagamya@dpo');
    await expect(page.getByRole('button', { name: 'Verify Access' })).toBeVisible();
    await page.getByRole('button', { name: 'Verify Access' }).click();
    await page.getByText('Synchronizing Encrypted Logs').click();
    await page.getByRole('button', { name: 'Logout' }).click();
    await page.getByRole('button', { name: 'Stay Logged In' }).click();
    await page.getByRole('button', { name: 'Logout' }).click();
    await page.getByRole('button', { name: 'Logout & Exit' }).click();
    await page.getByRole('link', { name: 'Staff Access' }).click();
    await page.locator('div').filter({ hasText: /^External Auditor$/ }).nth(1).click();
    await page.getByRole('textbox', { name: 'Auditor Username' }).click();
    await page.getByRole('textbox', { name: 'Auditor Username' }).fill('ext_auditor');
    await page.getByRole('textbox', { name: 'Access Key' }).fill('avagamya@audit');
    await page.getByRole('button', { name: 'Verify Access' }).click();
    await page.getByRole('button', { name: 'Certification' }).click();
    await page.getByRole('textbox', { name: 'Enter full policy name...' }).fill('HDFC Credit Card MITC ');
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Download Official Certificate' }).click();
    const download = await downloadPromise;
    await page.getByRole('link', { name: 'AVAGAMYA AVAGAMYA' }).click();
    await page.getByRole('button', { name: 'Logout & Exit' }).click();
    await page.getByRole('link', { name: 'Staff Access' }).click();
    await page.locator('div').filter({ hasText: 'Compliance Officer' }).nth(5).click();
    await page.getByRole('textbox', { name: 'Compliance Username' }).click();
    await page.getByRole('textbox', { name: 'Compliance Username' }).fill('comp_officer');
    await page.getByRole('textbox', { name: 'Access Key' }).fill('avagamya@comp');
    await page.getByRole('button', { name: 'Verify Access' }).click();
    await page.getByRole('button', { name: 'Sandbox' }).click();
    await page.getByRole('button', { name: 'Audit' }).click();
    await page.getByRole('button', { name: 'Choose File' }).click();
    await page.getByText('Compliance Officer Audit').click();
});