import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('/');
    // Bypass OTP Auth Flow for UI Testing
    await page.goto('/staff/modules');
    await page.getByRole('heading', { name: 'Data Protection Officer' }).click();
    await page.getByRole('textbox', { name: 'DPO Username' }).click();
    await expect(page.locator('form')).toContainText('Verify Access');
    await page.getByRole('textbox', { name: 'DPO Username' }).fill('dpo_admin');
    await page.getByRole('textbox', { name: 'Access Key' }).fill('avagamya@dpo');
    await expect(page.getByRole('button', { name: 'Verify Access' })).toBeVisible();
    await page.getByRole('button', { name: 'Verify Access' }).click();
    await page.getByText('Synchronizing Encrypted Logs').click();
    await page.getByRole('button', { name: 'Logout' }).click();
    await page.getByRole('button', { name: 'Stay Logged In' }).click();
    await page.getByRole('button', { name: 'Logout' }).click();
    await page.getByRole('button', { name: 'Logout & Exit' }).click();
    await page.goto('/staff/modules');
    await page.getByRole('heading', { name: 'Internal Auditor' }).click();
    await page.getByRole('textbox', { name: 'Auditor Username' }).click();
    await page.getByRole('textbox', { name: 'Auditor Username' }).fill('ext_auditor');
    await page.getByRole('textbox', { name: 'Access Key' }).fill('avagamya@audit');
    await page.getByRole('button', { name: 'Verify Access' }).click();
    await page.getByRole('button', { name: 'Certification' }).click();
    await page.getByRole('textbox', { name: 'Enter full policy name...' }).fill('HDFC Credit Card MITC ');
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Download Official Certificate' }).click();
    const download = await downloadPromise;
    await page.getByRole('link', { name: 'AVAGAMYA AVAGAMYA' }).click();
    await page.getByRole('button', { name: 'Logout & Exit' }).click();
    await page.goto('/staff/modules');
    await page.getByRole('heading', { name: 'Compliance Officer' }).click();
    await page.getByRole('textbox', { name: 'Compliance Username' }).click();
    await page.getByRole('textbox', { name: 'Compliance Username' }).fill('comp_officer');
    await page.getByRole('textbox', { name: 'Access Key' }).fill('avagamya@comp');
    await page.getByRole('button', { name: 'Verify Access' }).click();
    await page.getByRole('button', { name: 'Verify Access' }).click();
    await expect(page.getByRole('heading', { name: 'Compliance Command Center' })).toBeVisible();
    await expect(page.getByText('Policy Intelligence')).toBeVisible();
    await expect(page.getByText('Governance Sandbox')).toBeVisible();
});