-- SQL to create the awareness_facts table in Supabase
-- Run this in your Supabase SQL Editor: https://supabase.com/dashboard/project/_/sql

CREATE TABLE IF NOT EXISTS public.awareness_facts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    category TEXT NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    color_theme TEXT NOT NULL DEFAULT 'orange'
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.awareness_facts ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow anyone to read the data (Public Access)
CREATE POLICY "Allow public read access"
ON public.awareness_facts
FOR SELECT
TO public
USING (true);

-- Insert sample data
INSERT INTO public.awareness_facts (category, title, content, color_theme)
VALUES 
('Data Privacy', 'The DPDP Act 2023', 'India''s Digital Personal Data Protection Act empowers you with rights over your personal data, including the right to correction and erasure.', 'orange'),
('Safety Tip', 'PII Protection', 'Personally Identifiable Information (PII) like your Aadhaar number or DOB should only be shared with verified and trusted entities.', 'blue'),
('Financial Literacy', 'Understanding APR', 'The Annual Percentage Rate represents the total cost of credit, including interest and fees, expressed as a yearly rate.', 'orange'),
('Web Safety', 'Look for the Padlock', 'Always check for ''https://'' and the padlock icon in your browser''s address bar before entering sensitive information on any website.', 'blue');
